from ai.task import BaseTask
from ai.tools.hub_requests import verify_answer


class ConfigApplierAgent(BaseTask):
    """
    An agent responsible for applying generated wind turbine configurations.
    It retrieves the generated configurations and their corresponding unlock codes
    from memory, combines them, and sends them to the external service.
    """

    def __init__(self, agent_model, memory):
        """
        Initializes the ConfigApplierAgent.

        Args:
            agent_model: The underlying agent model.
            memory: The memory object for storing and retrieving data.
        """
        super().__init__(agent=agent_model, memory=memory, name="ConfigApplierAgent")

    def execute(self):
        """
        Executes the logic to prepare and apply wind turbine configurations.

        It fetches configurations and unlock codes from memory, matches them,
        and then sends the complete configurations to the external service
        via the `verify_answer` tool.
        Raises ValueError if an unlock code is missing for a generated configuration.
        """
        # Retrieve the current task name from memory.
        task_name = self.memory.get("task_name")
        # Retrieve the configurations generated by the ConfigGeneratorAgent.
        generated_configs_for_matching = self.memory.get(
            "generated_configs_for_matching"
        )
        # Retrieve the map of unlock codes obtained by the ResultsPollingAgent.
        unlock_codes = self.memory.get("unlockCodeGenerator_map")

        # Initialize a dictionary to hold the final configurations ready for sending.
        final_configs_to_send = {}
        # If there are generated configurations, proceed to match them with unlock codes.
        if generated_configs_for_matching:
            for date_str, config_data in generated_configs_for_matching.items():
                # Get the unlock code for the specific date/hour.
                unlock_code = unlock_codes.get(date_str)
                if not unlock_code:
                    # If an unlock code is missing, it's a critical error.
                    raise ValueError(f"Unlock code missing for config at {date_str}")
                # Combine the configuration data with its unlock code.
                final_configs_to_send[date_str] = {
                    **config_data,
                    "unlockCode": unlock_code,
                }

        # If there are final configurations to send, call the external service.
        if final_configs_to_send:
            # The 'action' is "config" and the 'configs' parameter contains the dictionary
            # of configurations keyed by date string, each including the unlock code.
            verify_answer(
                task_name, {"action": "config", "configs": final_configs_to_send}
            )
